# Fix colors over ssh
# set -g default-terminal "screen-256color"
# set -ga terminal-overrides ",xterm-256color*:Tc"
set -g default-terminal "tmux-256color"

# Enable mouse. Use shift, i.e. Shift+LeftClickDrag to highlight text. Esc to cancel
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e; send-keys =M'"

# Tmux Resurrect/Continuum
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Fix lag when using tmux
set -sg escape-time 10


# ================================================================================
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
