# Fix colors over ssh
# set -g default-terminal "screen-256color"
# set -ga terminal-overrides ",xterm-256color*:Tc"
set -g default-terminal "tmux-256color"


# Tmux Resurrect/Continuum
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
