---
name: Create Manual Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump type (patch, minor, major)"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.bump_version.outputs.new_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install chezmoi
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b ~/.local/bin

      - name: Add chezmoi to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          if [ -z "$LATEST_TAG" ]; then
            LATEST_TAG="v0.0.0"
          fi
          echo "Latest tag: $LATEST_TAG"
          echo "latest_tag=$LATEST_TAG" >> "$GITHUB_OUTPUT"

      - name: Bump version
        id: bump_version
        run: |
          echo "Bump type: ${{ github.event.inputs.bump }}"
          echo "Latest tag from get_tag: ${{ steps.get_tag.outputs.latest_tag }}"
          
          LATEST="${{ steps.get_tag.outputs.latest_tag }}"
          IFS='.' read -r MAJOR MINOR PATCH <<< "${LATEST#v}"

          BUMP="${{ github.event.inputs.bump }}"
          case "$BUMP" in
            major)
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            minor)
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            patch)
              PATCH=$((PATCH + 1))
              ;;
          esac

          NEW_TAG="$MAJOR.$MINOR.$PATCH"
          echo "Calculated new tag: $NEW_TAG"

          echo "new_tag=$NEW_TAG" >> "$GITHUB_OUTPUT"

      - name: Show output tag
        run: echo "New tag is ${{ steps.bump_version.outputs.new_tag }}"
    
  render:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install chezmoi
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b ~/.local/bin

      - name: Add chezmoi to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Create chezmoi config for CI
        run: |
          GIT_USER="github-actions[bot]"
          GIT_EMAIL="41898282+52949282+github-actions[bot]@users.noreply.github.com"
          
          cat <<EOF > .chezmoi.toml
          [data]
            name = "${GIT_USER}"
            email = "${GIT_EMAIL}"
          EOF

      - name: Create output directories
        run: |
          mkdir -p rendered/
          mkdir -p self_contained/
          mkdir -p release_assets/

      - name: Render dotfiles to output directory
        run: |
          chezmoi apply \
            --source $(pwd) \
            --config .chezmoi.toml \
            --config-format toml \
            --destination rendered/ \
            --keep-going \
            --no-tty \
            --verbose \
            --force

      - name: Add generated files to rendered/
        run: |
          echo "${{ needs.setup.outputs.new_tag }}" >> rendered/.version

      - name: Create installable chezmoi + dotfiles artifact
        run: |
          chezmoi generate install.sh > self_contained/install.sh

      - name: Add generated files
        run: |
          cat <<EOF > self_contained/README_BEFORE_INSTALL.txt
          ###########################################################################
          #                          !! WARNING !!                                  #
          #                                                                         #
          # Make a backup of your dots (~/.bashrc, ~/.bash_aliases, ~/.config, etc) #
          # before running the install.sh script!                                   #
          ###########################################################################

          Run ./install.sh to install chezmoi & apply the dotfiles.
          EOF

      - name: Add help text
        run: |
          cat <<EOF > rendered/README.txt
          Github: https://github.com/redjax/dotfiles.git

          ################
          # Instructions #
          ################

          MAKE A BACKUP! The steps below will overwrite your dotfiles with mine.

          Copy & paste the files in this directory to your \$HOME directory, opting to replace/overwrite existing files.
          Close & re-open your terminal (or log out and back in), or run exec \$SHELL to load the dotfiles.
          EOF

      - name: List files for debugging
        run: |
          echo "$(pwd) files:"
          ls -la .
          echo ""
          
          echo "Rendered files:"
          ls -la rendered/
          echo ""
          
          echo "Self-contained Chezmoi files:"
          ls -la self_contained/
          echo ""

      - name: Upload rendered files as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: rendered-files
          path: rendered/

  archive:
    needs:
      - render
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download rendered files (if using artifacts)
        uses: actions/download-artifact@v4
        with:
          name: rendered-files

      - name: Create release assets directory
        run: |
          mkdir -p release_assets/
          mkdir -p rendered/
          mkdir -p self_contained/

      - name: Create ZIP archive of self-contained chezmoi dotfiles
        run: |
          VERSION="${{ needs.setup.outputs.new_tag }}"
          ZIP_NAME="chezmoi_dotfiles-v${VERSION}.zip"
          zip -r "release_assets/${ZIP_NAME}" self_contained -x ".git/*" "scripts/prune_git_branches.sh"

      - name: Create TAR archive of self-contained chezmoi dotfiles
        run: |
          VERSION="${{ needs.setup.outputs.new_tag }}"
          TAR_NAME="chezmoi_dotfiles-v${VERSION}.tar.gz"
          tar -czvf "release_assets/${TAR_NAME}" --exclude=".git/*" --exclude="scripts/prune_git_branches.sh" .

      - name: Create ZIP archive of rendered dotfiles
        run: |
          VERSION="${{ needs.setup.outputs.new_tag }}"
          ZIP_NAME="dotfiles-v${VERSION}.zip"
          zip -r "release_assets/${ZIP_NAME}" rendered/ -x ".gitconfig" "chezmoistate.db"

      - name: Create TAR archive of rendered dotfiles
        run: |
          VERSION="${{ needs.setup.outputs.new_tag }}"
          TAR_NAME="dotfiles-v${VERSION}.tar.gz"
          tar -czf "release_assets/${TAR_NAME}" --exclude=".gitconfig" --exclude="chezmoistate.boltdb" rendered/

      - name: Upload release assets as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: release_assets/

  release:
    needs: 
      - archive
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download release assets (if using artifacts)
        uses: actions/download-artifact@v4
        with:
          name: release-assets
          path: release_assets/

      - name: Debug setup output in release
        run: |
          echo "Release tag from setup output: v${{ needs.setup.outputs.new_tag }}"

      - name: Create git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+52949282+github-actions[bot]@users.noreply.github.com"
          git tag "v${{ needs.setup.outputs.new_tag }}"
          git push origin "v${{ needs.setup.outputs.new_tag }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ needs.setup.outputs.new_tag }}"
          name: "v${{ needs.setup.outputs.new_tag }}"
          generate_release_notes: true
          token: ${{ secrets.RELEASE_TOKEN }}
          files: |
            release_assets/dotfiles-v${{ needs.setup.outputs.new_tag }}.tar.gz
            release_assets/dotfiles-v${{ needs.setup.outputs.new_tag }}.zip
            release_assets/chezmoi_dotfiles-v${{ needs.setup.outputs.new_tag }}.tar.gz
            release_assets/chezmoi_dotfiles-v${{ needs.setup.outputs.new_tag }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
